server:
  servlet:
    context-path: /weblog

image:
  folder: static/images

spring:
  datasource:
    url: jdbc:h2:mem:postdb;DB_CLOSE_DELAY=-1;DB_CLOSE_ON_EXIT=FALSE
    username: sa
    password: qwerty

  sql:
    init:
      mode: always
      schema-locations: classpath:schema.sql

  h2:
    console:
      enabled: true
